<a href="https://colab.research.google.com/github/adrianix2000/Application-to-introduce-pandemic-data-in-Poland/blob/master/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.__version__

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Arrays

In [11]:
x = np.array([1,3])
x

array([1, 3])

In [12]:
print(x)

[1 3]


In [13]:
type(x)

numpy.ndarray

In [14]:
x.ndim

1

In [15]:
x.shape

(2,)

In [16]:
x.size

2

In [17]:
x.dtype

dtype('int64')

In [19]:
x = np.array([1.3, 2.4, 1.4])
print(x)

[1.3 2.4 1.4]


In [20]:
x.dtype

dtype('float64')

2D Array

In [22]:
x = np.array([[1,2], [-3,1]])
print(x)

[[ 1  2]
 [-3  1]]


In [23]:
x.ndim

2

In [24]:
x.shape

(2, 2)

In [25]:
x = np.array([[1,2,3],[4,2,1]])
print(x)

[[1 2 3]
 [4 2 1]]


In [26]:
x.shape

(2, 3)